# Generated by Django 4.0.5 on 2023-05-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Github_issue',
        ),
    ]
