# Generated by Django 4.0.5 on 2023-05-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github_issue',
            name='issueId',
        ),
        migrations.AlterField(
            model_name='github_issue',
            name='issue_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
