# Generated by Django 4.0.5 on 2023-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_Dashboard', '0002_remove_github_issue_issueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github_issue',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='github_issue',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
