# Generated by Django 4.0.5 on 2023-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_Dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github_issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='github_issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
